In [1]:
#To perform and analysis of Logistic Regression Algorithm

In [2]:
#Name : Ranjeet Vijayrao Telkhade

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [5]:
data=pd.read_csv("iris.csv")

In [6]:
data.head()

150    4  setosa  versicolor  virginica
0  5.1  3.5     1.4         0.2          0
1  4.9  3.0     1.4         0.2          0
2  4.7  3.2     1.3         0.2          0
3  4.6  3.1     1.5         0.2          0
4  5.0  3.6     1.4         0.2          0

In [7]:
data.tail()

150    4  setosa  versicolor  virginica
145  6.7  3.0     5.2         2.3          2
146  6.3  2.5     5.0         1.9          2
147  6.5  3.0     5.2         2.0          2
148  6.2  3.4     5.4         2.3          2
149  5.9  3.0     5.1         1.8          2

In [8]:
data.shape

(150, 5)

In [9]:
data.size

750

In [10]:
data.ndim

2

In [11]:
data.isna()

150      4  setosa  versicolor  virginica
0    False  False   False       False      False
1    False  False   False       False      False
2    False  False   False       False      False
3    False  False   False       False      False
4    False  False   False       False      False
..     ...    ...     ...         ...        ...
145  False  False   False       False      False
146  False  False   False       False      False
147  False  False   False       False      False
148  False  False   False       False      False
149  False  False   False       False      False

[150 rows x 5 columns]

In [12]:
data.isna().any()

150           False
4             False
setosa        False
versicolor    False
virginica     False
dtype: bool

In [13]:
data.isna().sum()

150           0
4             0
setosa        0
versicolor    0
virginica     0
dtype: int64

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x = np.arange(1,25).reshape(12,2)
y = np.array([0,1,1,0,1,0,0,1,1,0,1,0])

In [19]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [20]:
x_train

array([[17, 18],
       [11, 12],
       [ 5,  6],
       [ 3,  4],
       [23, 24],
       [ 9, 10],
       [15, 16],
       [ 7,  8],
       [13, 14]])

In [21]:
x_test

array([[21, 22],
       [19, 20],
       [ 1,  2]])

In [22]:
y_train

array([1, 0, 1, 1, 0, 1, 1, 0, 0])

In [23]:
y_test

array([1, 0, 0])

In [28]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression().fit(x_train,y_train)
model.score(x_train, y_train)*100

44.44444444444444

In [29]:
ypred=model.predict(x_test)

In [30]:
ypred

array([0, 0, 1])

In [32]:
from sklearn.metrics import r2_score,mean_absolute_error

In [33]:
mean_absolute_error(y_test,ypred)

np.float64(0.6666666666666666)